# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jmx:
    enabled: false
  main:
    banner-mode: OFF
  lifecycle:
    timeout-per-shutdown-phase: 20s

# ======================================================================================================================
# = WEB SERVER
# ======================================================================================================================
server:
  shutdown: graceful

# ======================================================================================================================
# = ACTUATOR - ALL METRICS OVER HTTP INSTEAD OF JMX
# ======================================================================================================================
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: '*'

# ======================================================================================================================
# = SPRINGFOX - SWAGGER / OPENAPI
# ======================================================================================================================
springfox:
  basePackage: 'com.github.ronlievens.demo.xsd.controller'
  paths:
    - '/api/v1/user.*'
  title: 'Demo XSD to Service REST/XML API'
  description: ''
  version: @project.version@

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  level:
    root: WARN
    springfox: INFO
    com:
      github:
        ronlievens: TRACE
